#ifndef DEFAULTCONFIG_H
#define DEFAULTCONFIG_H

#define CONFIG_PATH "config.txt"

#define DEFAULT_NUMBER_STATIONS 3
#define DEFAULT_NUMBER_ASTEROIDS 20
#define DEFAULT_MAP_WIDTH 50
#define DEFAULT_MAP_HEIGHT 50
#define DEFAULT_MAXIMUM_QUANTITY_PEPENIO 200
#define DEFAULT_MAXIMUM_QUANTITY_ROBERTERIO 200

#endif