#ifndef DEFAULTCONFIG_H
#define DEFAULTCONFIG_H

#define CONFIG_PATH "config.txt"
#define SHARED_MEMORY_PATH "/shared-map-satn"
#define SERVER_MOVEMENT_COMMUNICATION_QUEUE_PATH "/movement-communication-queue-satn"
#define SERVER_EXTRACTION_COMMUNICATION_QUEUE_PATH "/extraction-communication-queue-satn"
#define SERVER_STATION_WARNING_COMMUNICATION_QUEUE_PATH "/station-warning-communication-queue-satn"
#define SERVER_CLIENT_INITIALIZATION_QUEUE_PATH "/initialization-queue-satn"

#define DEFAULT_AMOUNT_MESSAGES_QUEUES 100
#define DEFAULT_NUMBER_STATIONS 3
#define DEFAULT_NUMBER_ASTEROIDS 20
#define DEFAULT_MAP_WIDTH 30
#define DEFAULT_MAP_HEIGHT 20
#define DEFAULT_MAXIMUM_QUANTITY_DEUTERIO 200
#define DEFAULT_MAXIMUM_QUANTITY_MUTEXIO 300
#define DEFAULT_MAXIMUM_QUANTITY_SEMAFORITA 200
#define DEFAULT_MAXIMUM_QUANTITY_KERNELIO 100

#endif