#ifndef DEFAULTCONFIG_H
#define DEFAULTCONFIG_H

#define CONFIG_PATH "config.txt"
#define SHARED_MEMORY_PATH "/shared-map-satn"

#define DEFAULT_NUMBER_STATIONS 3
#define DEFAULT_NUMBER_ASTEROIDS 20
#define DEFAULT_MAP_WIDTH 50
#define DEFAULT_MAP_HEIGHT 50
#define DEFAULT_MAXIMUM_QUANTITY_DEUTERIO 200
#define DEFAULT_MAXIMUM_QUANTITY_MUTEXIO 300
#define DEFAULT_MAXIMUM_QUANTITY_SEMAFORITA 200
#define DEFAULT_MAXIMUM_QUANTITY_KERNELIO 100

#endif